import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import type { SubmitHandler } from "react-hook-form";
import { useForm } from "react-hook-form";

const d = new Date();

const year = d.getFullYear();
const month = d.getMonth() + 1;
const date = d.getDate();
const hour = d.getHours();
const minute = d.getMinutes();

type FormValues = {
  text: string;
};

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm<FormValues>();

  const [arr, setArr] = useState<string[]>([]);

  console.log(arr);

  const onSubmit: SubmitHandler<FormValues> = (data) => {
    setArr((arr) => [...arr, data.text]);
    // reset(register);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-9/12 py-24 mx-auto">
        {arr.map((value) => {
          return <div key={value} className="border-t w-full">
            value
          </div>;
        })}
        <form onSubmit={handleSubmit(onSubmit)}>
          <textarea
            {...register("text")}
            className="block border border-black py-2 px-1 my-5 mx-auto w-9/12 bg-white bg-opacity-10"
          />
          <button onSubmit={handleSubmit(onSubmit)}>送信</button>
        </form>
      </div>
    </div>
  );
};

export default Home;
