import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import type { SubmitHandler } from "react-hook-form";
import { useForm } from "react-hook-form";

const d = new Date();

const year = d.getFullYear();
const month = d.getMonth() + 1;
const date = d.getDate();
const hour = d.getHours();
const minute = d.getMinutes();

type FormValues = {
  text: string;
};

const Home: NextPage = () => {
  const { register, handleSubmit, reset } = useForm<FormValues>();

  const [arr, setArr] = useState<string[]>([]);

  console.log(arr);

  const onSubmit: SubmitHandler<FormValues> = (data) => {
    if (data.text === "") {
      return false;
    }
    setArr((arr) => [...arr, data.text]);
    reset();
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-9/12 py-24 mx-auto">
        {arr.map((value) => {
          return (
            <div key={value} className="border-t w-9/12 mx-auto flex py-3">
              <h3 className="text-6xl font-bold mx-4">3</h3>
              <div className="my-2">
                <p className="text-lg font-bold">あなた</p>
                <p>{value}</p>
                </div>
            </div>
          );
        })}
        <form onSubmit={handleSubmit(onSubmit)}>
          <textarea
            {...register("text")}
            className="block border border-black py-2 px-1 my-5 mx-auto w-9/12 bg-white bg-opacity-10"
          />
          <button onSubmit={handleSubmit(onSubmit)}>送信</button>
        </form>
      </div>
    </div>
  );
};

export default Home;
